### ISSUE TITLE
Format of "ref_gene.txt"

### ISSUE THREAD

**Issue by adamtongji** [WeiqiangZhou/BIRD#1]
Hi,
I met a problem when using "match_gene.sh".  I used fpkm file in example folder as input file and latest ensembl gtf file as second parameter.  However, the second column of output file is all "0". 

Do you have examples of "ref_gene.txt" or example format of BIRD input file?
Thanks!

**Comment by WeiqiangZhou** [comment]
You should download the release version of BIRD from https://github.com/WeiqiangZhou/BIRD/releases/download/v1.0.3/BIRD_v1.0.3.zip

It contains a folder called "model". The ref_gene.txt file is located within that folder. You should use this file instead of your own ensemble gif file as the second parameter in preparing the input file for BIRD.

"match_gene.sh" only converts FPKM tracks obtained from cufflinks. If you have an FPKM data matrix, you should check the section "For RNA-seq with FPKM data matrix".

**Comment by adamtongji** [comment]
Thanks a lot for your prompt response!  And I downloaded the full version of "BIRD v1.0.3".
  
I found that the ref_gene.txt file contains only human hg19 Ensembl genes, but not for mouse.   Will you extend your model to other genomes like mouse genome in the future?

Thanks again for your excellent work!  It would be great if your algorithm updates for more genomes library~

**Comment by WeiqiangZhou** [comment]
Thank you for your suggestions. We are actively working on extending the prediction model to mouse. We will release the mouse prediction model soon.
